Currency_converter/Currency_converter/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('convert/', include('convert.urls')),
]

Currency_converter/convert/urls.py
from django.urls import path

from . import views
from .views import CurrencyRateListView

app_name = 'convert'
urlpatterns = [
    path('', views.index, name='index'),  # <-- updated URL path for home page
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('<str:currency_from>-<str:currency_to>/', CurrencyRateListView.as_view(), name='currency_rates'),
]

Currency_converter/convert/models.py
from django.db import models


class Provider(models.Model):
    name = models.CharField(max_length=200)
    website = models.CharField(max_length=500)
    last_update = models.DateTimeField()
    logo = models.ImageField(upload_to='logos')
    transaction_time = models.IntegerField()
    is_neutral = models.BooleanField()

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class CurrencyRate(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    currency_from = models.ForeignKey(Currency, on_delete=models.CASCADE, related_name='curency_from', null=True)
    currency_to = models.ForeignKey(Currency, on_delete=models.CASCADE, related_name='curency_to', null=True)
    exchange_rate = models.DecimalField(decimal_places=4, max_digits=16)
    date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}: {} to {}  - {} at {}".format(
            self.provider.name,
            self.currency_from.code,
            self.currency_to.code,
            self.exchange_rate,
            self.date_time)

Currency_converter/convert/views.py
from django.db.models import OuterRef, Subquery
from django.shortcuts import render

from .models import Provider, Currency, CurrencyRate
from .Spiders import Scrapers
from django.views.generic import ListView
import matplotlib.pyplot as plt
import mplcursors
import mpld3


def index(request):
    scrapers = Scrapers()
 #   scrapers.run()

    provider_list = Provider.objects.all()
    neutral_provider = Provider.objects.get(is_neutral__exact=True)
    currency_list = Currency.objects.all()

    usd = currency_list.get(code__exact='USD')
    pen = currency_list.get(code__exact='PEN')
    usd_to_pen_rate_list = CurrencyRate.objects.filter(
        currency_from=usd,
        currency_to=pen,
        date_time=Subquery(
            CurrencyRate.objects.filter(
                currency_from=OuterRef('currency_from'),
                currency_to=OuterRef('currency_to'),
                provider=OuterRef('provider')
            ).order_by('-date_time').values('date_time')[:1]
        )
    ).values(
        'provider',
        'exchange_rate',
        'date_time',
    )

    pen_to_usd_rate_list = CurrencyRate.objects.filter(
        currency_from=pen,
        currency_to=usd,
        date_time=Subquery(
            CurrencyRate.objects.filter(
                currency_from=OuterRef('currency_from'),
                currency_to=OuterRef('currency_to'),
                provider=OuterRef('provider')
            ).order_by('-date_time').values('date_time')[:1]
        )
    ).values(
        'provider',
        'exchange_rate',
        'date_time',
    )

    usd_to_pen_chart = create_rate_chart(
        'USD',
        'PEN',
        provider_list,
    )

    pen_to_usd_chart = create_rate_chart(
        'PEN',
        'USD',
        provider_list
    )

    context = {
        'provider_list': provider_list,
        'currency_list': currency_list,
        'USDtoPEN_rate_list': usd_to_pen_rate_list,
        'PENtoUSD_rate_list': pen_to_usd_rate_list,
        'neutral_provider': neutral_provider,
        'chart1': usd_to_pen_chart,
        'chart2': pen_to_usd_chart,
    }
    return render(request, 'convert/index.html', context)


class CurrencyRateListView(ListView):
    model = CurrencyRate
    template_name = 'convert/currency_rate_list.html'

    def get_queryset(self):
        currency_from = Currency.objects.get(code=self.kwargs['currency_from'])
        currency_to = Currency.objects.get(code=self.kwargs['currency_to'])

        # Filter the CurrencyRate queryset to only include the latest rates for each provider
        qs = CurrencyRate.objects.filter(
            currency_from=currency_from,
            currency_to=currency_to,
            date_time=Subquery(
                CurrencyRate.objects.filter(
                    currency_from=OuterRef('currency_from'),
                    currency_to=OuterRef('currency_to'),
                    provider=OuterRef('provider')
                ).order_by('-date_time').values('date_time')[:1]
            )
        ).values(
            'provider',
            'exchange_rate',
            'date_time',
        )

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['provider_list'] = Provider.objects.all()
        context['currency_from'] = Currency.objects.get(code=self.kwargs['currency_from'])
        context['currency_to'] = Currency.objects.get(code=self.kwargs['currency_to'])

        context['chart'] = create_rate_chart(self.kwargs['currency_from'],
                                             self.kwargs['currency_to'],
                                             Provider.objects.all())
        return context


def create_rate_chart(form_code, to_code, provider_list):
    fig, ax = plt.subplots(figsize=(6, 4))

    for provider in provider_list:
        # Get the currency rate data for each provider
        rates = CurrencyRate.objects \
            .filter(provider=provider, currency_from__code=form_code, currency_to__code=to_code) \
            .order_by('date_time')
        dates = [rate.date_time for rate in rates]
        rates = [rate.exchange_rate for rate in rates]
        print(provider.name)
        for date in dates:
            print(date)
        # Add a line to the graph for each provider
        line, = ax.plot(dates, rates, label=provider.name)

        # Add annotation to show provider name on hover
        mplcursors.cursor(line).connect(
            "add", lambda sel: sel.annotation.set_text(provider.name))

    # Add labels and legend
    ax.set_xlabel('Date')
    ax.set_ylabel('{} to {} Exchange Rate'.format(form_code, to_code))
    ax.set_title('{} to {} Exchange Rates'.format(form_code, to_code))
    ax.legend()

    # Convert the plot to an interactive HTML format using mpld3
    interactive_graphic = mpld3.fig_to_html(fig)

    return interactive_graphic


def about(request):
    return render(request, 'convert/about.html')


def contact(request):
    return render(request, 'convert/contact.html')

Currency_converter/convert/templates/convert/about.html
{% extends 'convert/base.html' %}

{% block content %}
    <h1>About</h1>
    <p>This is a currency conversion app built with Django.</p>
{% endblock %}

Currency_converter/convert/templates/convert/base.html
{% load static %}     <!-- load all static files  -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- import style sheet  -->
    <link rel="stylesheet" href="{% static 'convert/main.css' %}">
    <!-- import javascript   -->
    <script src="{% static 'convert/script.js' %}"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-2.0.0.min.js"></script>
	<title>Currency Exchange Rates</title>

</head>
<body >
    <nav>
        <ul>
            <!-- links for the main menu  -->
            <li><a href="{% url 'convert:index' %}">Home</a></li>
            <li><a href="{% url 'convert:about' %}">About</a></li>
            <li><a href="{% url 'convert:contact' %}">Contact</a></li>
        </ul>
    </nav>
   <div class="container">
      <div class="side-menu">
          <h3>Currencies:</h3>
        <ul>
            <!-- links for the side menu  -->
            <li><a href="{% url 'convert:currency_rates' currency_from='USD' currency_to='PEN' %}">USD to PEN</a></li>
            <li><a href="{% url 'convert:currency_rates' currency_from='PEN' currency_to='USD' %}">PEN to USD</a></li>
        </ul>
      </div>
        <div class="page_content">
      <div class="content">
        {% block content %}
                <!-- content form all pages extending this base  -->
        {% endblock %}
      </div>
   </div>
    </div>
    <footer>
        <p>&copy; 2023 ExchangeRates</p>
    </footer>
</body>
</html>

Currency_converter/convert/templates/convert/contact.html
{% extends 'convert/base.html' %}

{% block content %}
  <h1>Contact Us</h1>
  <p>Fill out the form below to get in touch with us.</p>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name">
    </div>
    <div class="form-group">
      <label for="email">Email address</label>
      <input type="email" class="form-control" id="email" name="email">
    </div>
    <div class="form-group">
      <label for="message">Message</label>
      <textarea class="form-control" id="message" name="message" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

Currency_converter/convert/templates/convert/currency_rate_list.html
{% extends 'convert/base.html' %}
{% load static %}



{% block content %}
  <h1>Currency Rates: {{ currency_from.name }} to {{ currency_to.name }}</h1>

  <table onload="highlight_highest_lowest_currency_page()" id="myTable" class="sortable">
    <thead>
      <tr>
        <th>Provider</th>
          <th>Transaction time (h)</th>
        <th>Exchange Rate</th>
        <th>Last updated</th>
      </tr>
    </thead>
    <tbody>
    {% for provider in provider_list %}
         {% if not provider.is_neutral %}
                     <tr>
                         <td ><a href="{{ provider.website }}">{{ provider.name }}</a></td>
                        <td >{{ provider.transaction_time }}</td>
                      {% for rate in object_list %}
                            {% if rate.provider == provider.id %}
                                  <td class="rate_one" value="{{ rate.exchange_rate}}">{{ rate.exchange_rate }}</td>
                                  <td>{{ rate.date_time }}</td>
                          {% endif %}
                      {% endfor %}
                     </tr>
        {% endif %}
    {% endfor %}
    </tbody>
  </table>
    <div id="chart" style="display: flex; flex-direction: row;">
        {% if chart %}
            <div style="flex: 1;">{{ chart|safe }}</div>
        {% endif %}

    </div>
    <script>
    // Add an event listener to the window object to call the function when the page finishes loading
    window.addEventListener('load', function() {
        highlight_highest_lowest_currency_page();
    });
</script>
{% endblock %}

Currency_converter/convert/templates/convert/index.html
{% extends 'convert/base.html' %}

{% block content %}

	<h1>Currency Exchange Rates</h1>
    <table id="neutrTable">
        <thead>
			<tr>
				<th > </th>
				<th >USD to PEN</th>
                <th >PEN to USD</th>
			</tr>
		</thead>

                <tr >
                    <td ><a href="{{ neutral_provider.website }}">{{ neutral_provider.name }}</a></td>
                    {% for rate in USDtoPEN_rate_list %}
                        {% if rate.provider == neutral_provider.id  %}
                            <td class="neutr-rate" value="{{ rate.exchange_rate}}">{{ rate.exchange_rate}}</td>
                        {% endif %}
                    {% endfor %}
                    {% for rate in PENtoUSD_rate_list %}
                        {% if rate.provider == neutral_provider.id  %}
                            <td class="neutr-rate" value="{{ rate.exchange_rate}}">{{ rate.exchange_rate}}</td>
                        {% endif %}
                    {% endfor %}
                </tr>


    </table>
	<!-- Table to display exchange rates -->
    <table onload="highlight_highest_lowest()" id="myTable" class="sortable">
        <thead>
			<tr>
				<th >Company</th>
				<th >USD to PEN</th>
                <th >PEN to USD</th>
			</tr>
		</thead>
        {% if provider_list %}
            {% for provider in provider_list %}
                {% if not provider.is_neutral %}
                <tr >
                    <td ><a href="{{ provider.website }}">{{ provider.name }}</a></td>
                    {% for rate in USDtoPEN_rate_list %}
                        {% if rate.provider == provider.id  %}
                            <td class="rate" value="{{ rate.exchange_rate}}">{{ rate.exchange_rate}}</td>
                        {% endif %}
                    {% endfor %}
                    {% for rate in PENtoUSD_rate_list %}
                        {% if rate.provider == provider.id  %}
                            <td class="rate" value="{{ rate.exchange_rate}}">{{ rate.exchange_rate}}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
                {% endif %}
            {% endfor %}
        {% else %}
            <p>No Providers are available.</p>
        {% endif %}

    </table>
    <div id="charts" style="display: flex; flex-direction: row;">
        {% if chart1 %}
            <div style="flex: 1;">{{ chart1|safe }}</div>
        {% endif %}
        {% if chart2 %}
            <div style="flex: 1;">{{ chart2|safe }}</div>
        {% endif %}
    </div>

<script>
    // Add an event listener to the window object to call the function when the page finishes loading
    window.addEventListener('load', function() {
        highlight_highest_lowest();
    });

</script>

{% endblock %}